/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.MateriaisDAO;
import DTO.MateriaisDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frmMateriaisVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmTrabalhosVIEW
     */
    public frmMateriaisVIEW() {
        initComponents();
       ListarValoresMateriais();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricao = new javax.swing.JTextArea();
        brn_salvar = new javax.swing.JButton();
        brn_alterar = new javax.swing.JButton();
        btn_carregar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_materiais = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trabalhos");

        jLabel1.setText("Codigo:");

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Descricao:");

        txt_descricao.setColumns(20);
        txt_descricao.setRows(5);
        jScrollPane1.setViewportView(txt_descricao);

        brn_salvar.setText("Cadastrar");
        brn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_salvarActionPerformed(evt);
            }
        });

        brn_alterar.setText("Alterar");
        brn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_alterarActionPerformed(evt);
            }
        });

        btn_carregar.setText("Carregar Campo");
        btn_carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carregarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        tabela_materiais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "DESCRICAO"
            }
        ));
        jScrollPane4.setViewportView(tabela_materiais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCodigo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(brn_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(brn_alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_carregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brn_salvar)
                    .addComponent(brn_alterar)
                    .addComponent(btn_carregar)
                    .addComponent(btn_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_salvarActionPerformed
        try {
            CadastrarMateriais();
        } catch (SQLException ex) {
            Logger.getLogger(frmMateriaisVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListarValoresMateriais();
        LimparCampos();
      
    }//GEN-LAST:event_brn_salvarActionPerformed

    private void brn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_alterarActionPerformed
        try {
            AlterarMateriais();
        } catch (SQLException ex) {
            Logger.getLogger(frmMateriaisVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListarValoresMateriais();
    }//GEN-LAST:event_brn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        try {
            ExcluirMaterial();
        } catch (SQLException ex) {
            Logger.getLogger(frmMateriaisVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListarValoresMateriais();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_carregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carregarActionPerformed
       CarregarCampos();
    }//GEN-LAST:event_btn_carregarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMateriaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMateriaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMateriaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMateriaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMateriaisVIEW().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_alterar;
    private javax.swing.JButton brn_salvar;
    private javax.swing.JButton btn_carregar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabela_materiais;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txt_descricao;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables

    private void ListarValoresMateriais(){
        MateriaisDAO objmateriaisdao = new MateriaisDAO();
        
        DefaultTableModel model = (DefaultTableModel) tabela_materiais.getModel();
        model.setNumRows(0);
        
        ArrayList<MateriaisDTO> lista = objmateriaisdao.PesquisarMaterial();
        
        for(int num=0; num<lista.size(); num++){
            model.addRow(new Object[]{
                lista.get(num).getId_materiais(),
                lista.get(num).getNome_materiais(),
                lista.get(num).getDescricao_materiais()
            
            });
        }
    }
    
    private void CarregarCampos(){
        int setar = tabela_materiais.getSelectedRow();
        txtCodigo.setText(tabela_materiais.getModel().getValueAt(setar, 0).toString());
        txt_nome.setText(tabela_materiais.getModel().getValueAt(setar, 1).toString());
        txt_descricao.setText(tabela_materiais.getModel().getValueAt(setar, 2).toString());
    }
    
    private void CadastrarMateriais() throws SQLException{
        String nome,descricao;
        
        nome = txt_nome.getText();
        descricao = txt_descricao.getText();
        
        MateriaisDTO objmateriaisdto = new MateriaisDTO();
        objmateriaisdto.setNome_materiais(nome);
        objmateriaisdto.setDescricao_materiais(descricao);
        
        MateriaisDAO objmateriaisdao = new MateriaisDAO();
        objmateriaisdao.cadastrarMaterial(objmateriaisdto);     
    }
    
    private void LimparCampos(){
        txtCodigo.setText("");
        txt_nome.setText("");
        txt_descricao.setText("");
    }
    
    public void AlterarMateriais() throws SQLException{
        int id_materiais;
        String nome_materiais,descricao_materiais;
        
        id_materiais = Integer.parseInt(txtCodigo.getText());
        nome_materiais = txt_nome.getText();
        descricao_materiais = txt_descricao.getText();
        
        MateriaisDTO objmateriaisdto = new MateriaisDTO();
        objmateriaisdto.setId_materiais(id_materiais);
        objmateriaisdto.setNome_materiais(nome_materiais);
        objmateriaisdto.setDescricao_materiais(descricao_materiais);
        
        MateriaisDAO objmateriaisdao = new MateriaisDAO();
        objmateriaisdao.AlterarMaterial(objmateriaisdto);
            
    }
    
    private void ExcluirMaterial() throws SQLException{
        int id_materiais;
        
        id_materiais = Integer.parseInt(txtCodigo.getText());
        
        MateriaisDTO objmateriaisdto = new MateriaisDTO();
        objmateriaisdto.setId_materiais(id_materiais);
        
        MateriaisDAO objmateriaisdao = new MateriaisDAO();
        objmateriaisdao.ExcluirMaterial(objmateriaisdto);
        
    }
}
