/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.TrabalhosDAO;
import DTO.TrabalhosDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmTrabalhoslVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmFerramentaVIEW
     */
    public frmTrabalhoslVIEW() {
        initComponents();
        listarValoresTrabalhos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_contratante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricao = new javax.swing.JTextArea();
        btn_salvar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_carregar = new javax.swing.JButton();
        btn_ecluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_trabalhos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Materiais");

        jLabel1.setText("Codigo:");

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Contratante:");

        txt_contratante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contratanteActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone:");

        txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneActionPerformed(evt);
            }
        });

        jLabel4.setText("Endereco:");

        txt_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enderecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Descricao:");

        txt_descricao.setColumns(20);
        txt_descricao.setRows(5);
        jScrollPane1.setViewportView(txt_descricao);

        btn_salvar.setText("Cadastrar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_carregar.setText("Carregar Campo");
        btn_carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carregarActionPerformed(evt);
            }
        });

        btn_ecluir.setText("Excluir");
        btn_ecluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecluirActionPerformed(evt);
            }
        });

        tabela_trabalhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "CONTRATANTE", "TELEFONE", "ENDERECO","DESCRICAO"
            }
        ));
        jScrollPane2.setViewportView(tabela_trabalhos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_salvar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo)
                                .addComponent(txt_contratante, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(txt_telefone)
                                .addComponent(txt_endereco))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_alterar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_carregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ecluir)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_contratante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterar)
                    .addComponent(btn_salvar)
                    .addComponent(btn_carregar)
                    .addComponent(btn_ecluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        try {
            AlterarTrabalhos();
        } catch (SQLException ex) {
            Logger.getLogger(frmTrabalhoslVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarValoresTrabalhos();
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneActionPerformed

    private void txt_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enderecoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
       CadastrarTrabalhos();
       listarValoresTrabalhos();
       LimparCampos();
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_contratanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contratanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contratanteActionPerformed

    private void btn_carregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carregarActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btn_carregarActionPerformed

    private void btn_ecluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ecluirActionPerformed
        try {
            ExcluirTrabalhos();
        } catch (SQLException ex) {
            Logger.getLogger(frmTrabalhoslVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarValoresTrabalhos();
          
    }//GEN-LAST:event_btn_ecluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrabalhoslVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrabalhoslVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrabalhoslVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrabalhoslVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrabalhoslVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_carregar;
    private javax.swing.JButton btn_ecluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_trabalhos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txt_contratante;
    private javax.swing.JTextArea txt_descricao;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

private void listarValoresTrabalhos(){
    try {
        TrabalhosDAO objfuncionariodao = new TrabalhosDAO();
        
        DefaultTableModel model = (DefaultTableModel) tabela_trabalhos.getModel();
        model.setNumRows(0);
        
        ArrayList<TrabalhosDTO> lista = objfuncionariodao.PesquisarTrabalhos();
        
        for(int num=0; num<lista.size(); num++){
            model.addRow(new Object[]{
                lista.get(num).getId_trabalhos(),
                lista.get(num).getContratante_trabalhos(),
                lista.get(num).getTelefone_trabalhos(),
                lista.get(num).getEndereco_trabalhos(),
                lista.get(num).getDescricao_trabalhos()
            });
                
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void CarregarCampos(){
    int setar = tabela_trabalhos.getSelectedRow();
    txtCodigo.setText(tabela_trabalhos.getModel().getValueAt(setar,0).toString());
    txt_contratante.setText(tabela_trabalhos.getModel().getValueAt(setar, 1).toString());
    txt_telefone.setText(tabela_trabalhos.getModel().getValueAt(setar, 2).toString());
    txt_endereco.setText(tabela_trabalhos.getModel().getValueAt(setar, 3).toString());
    txt_descricao.setText(tabela_trabalhos.getModel().getValueAt(setar, 4).toString());
}

private void CadastrarTrabalhos(){
    String nome, endereco,telefone,descricao;
       
       nome = txt_contratante.getText();
       telefone = txt_telefone.getText();
       endereco = txt_endereco.getText();
       descricao = txt_descricao.getText();
       
        TrabalhosDTO objtrabalhosdto = new TrabalhosDTO();
        objtrabalhosdto.setContratante_trabalhos(nome);
        objtrabalhosdto.setTelefone_trabalhos(endereco);
        objtrabalhosdto.setEndereco_trabalhos(telefone);
        objtrabalhosdto.setDescricao_trabalhos(descricao);
        
        TrabalhosDAO objtrabalhosdao = new TrabalhosDAO();
        try {
            objtrabalhosdao.cadastrarTrabalhos(objtrabalhosdto);
        } catch (SQLException ex) {
            Logger.getLogger(frmFuncionarioVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
}

private void LimparCampos(){
    txtCodigo.setText("");
    txt_contratante.setText("");
    txt_endereco.setText("");
    txt_telefone.setText("");
    txt_descricao.setText("");
    txt_contratante.requestFocus();

}

public void AlterarTrabalhos() throws SQLException{
    int id_trabalhos;
    String contratnate_trabalhos, endereco_trabalhos,telefone_trabalhos,descricao_trabalhos;
    
    id_trabalhos = Integer.parseInt(txtCodigo.getText());
    contratnate_trabalhos = txt_contratante.getText();
    endereco_trabalhos = txt_endereco.getText();
    telefone_trabalhos = txt_telefone.getText();
    descricao_trabalhos = txt_descricao.getText();
    
    TrabalhosDTO objtrabalhosdto = new TrabalhosDTO();
    objtrabalhosdto.setId_trabalhos(id_trabalhos);
    objtrabalhosdto.setContratante_trabalhos(contratnate_trabalhos);
    objtrabalhosdto.setEndereco_trabalhos(endereco_trabalhos);
    objtrabalhosdto.setTelefone_trabalhos(telefone_trabalhos);
    objtrabalhosdto.setDescricao_trabalhos(descricao_trabalhos);
            
    
    
    TrabalhosDAO objtrabalhosdao = new TrabalhosDAO();
    objtrabalhosdao.AlterarTrabalho(objtrabalhosdto);
    
}

private void ExcluirTrabalhos() throws SQLException{
    int id_trabalhos;
    
    id_trabalhos = Integer.parseInt(txtCodigo.getText());
    
    TrabalhosDTO objtrabalhosdto = new TrabalhosDTO();
    objtrabalhosdto.setId_trabalhos(id_trabalhos);
    
    TrabalhosDAO objtrabalhosdao = new TrabalhosDAO();
    objtrabalhosdao.ExcluirTrabalhos(objtrabalhosdto);
    
}


}


